# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab961994e2808ec30a4493d2cb9801d10de9f8438e1a77a3c7bd0d11b5a5b8d10b6e187b1f5a7061e20546ecec3d70f03cb749c634bc0304e038922186f811d

test:
  secret_key_base: f01a690cc509d9757f7ca5bd3e5a7d6252ace9cc462c89a9de75d1db49558f6335d31abd9462a316bbd16549547dff87ce6c519362c66b32345e2a0633bd6c09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
